approvedGitRepositories:
  - "**"

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  vite-plugin-dts@*:
    peerDependencies:
      typescript: "*"
